const express=require('express');const http=require('http');const fs=require('fs');
const {WebSocketServer}=require('ws');
const app=express();const server=http.createServer(app);const wss=new WebSocketServer({server});
app.use(express.json());app.use(express.static('public'));
const SAVE='data.json';let users={};const rooms={};
const MAP_W=3000,MAP_H=3000,TICK=1000/60;
const WEAPONS={pistol:{name:'手枪',dmg:18,ammo:999,cd:250,spd:12},smg:{name:'冲锋枪',dmg:12,ammo:50,cd:70,spd:15,spread:.15},rifle:{name:'步枪',dmg:28,ammo:30,cd:100,spd:18},shotgun:{name:'霰弹枪',dmg:15,ammo:8,cd:500,spd:10,pellets:5,spread:.28},sniper:{name:'狙击枪',dmg:65,ammo:5,cd:1200,spd:28},rpg:{name:'火箭筒',dmg:100,ammo:3,cd:2500,spd:6,explosive:true}};
function uid(){return Math.random().toString(36).slice(2,10);}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function save(){try{fs.writeFileSync(SAVE,JSON.stringify(users));}catch(e){}}
try{if(fs.existsSync(SAVE))users=JSON.parse(fs.readFileSync(SAVE,'utf8'));}catch(e){}
const TERRAIN=[];
for(let y=0;y<30;y++){TERRAIN[y]=[];for(let x=0;x<30;x++){const cx=(x-15)*100+MAP_W/2,cy=(y-15)*100+MAP_H/2;const d=Math.hypot(cx-MAP_W/2,cy-MAP_H/2);TERRAIN[y][x]=d<400?2:d<600?3:Math.random()<.3?1:0;}}
const BUILDINGS=[{x:200,y:200,w:180,h:140},{x:MAP_W-380,y:200,w:180,h:140},{x:200,y:MAP_H-340,w:180,h:140},{x:MAP_W-380,y:MAP_H-340,w:180,h:140},{x:MAP_W/2-140,y:MAP_H/2-120,w:280,h:240},{x:700,y:800,w:140,h:110},{x:MAP_W-840,y:800,w:140,h:110},{x:700,y:MAP_H-910,w:140,h:110},{x:MAP_W-840,y:MAP_H-910,w:140,h:110},{x:MAP_W/2-60,y:300,w:120,h:90},{x:MAP_W/2-60,y:MAP_H-390,w:120,h:90},{x:300,y:MAP_H/2-70,w:90,h:140},{x:MAP_W-390,y:MAP_H/2-70,w:90,h:140},{x:400,y:400,w:120,h:90},{x:MAP_W-520,y:400,w:120,h:90},{x:400,y:MAP_H-490,w:120,h:90},{x:MAP_W-520,y:MAP_H-490,w:120,h:90}];
app.post('/api/register',(req,res)=>{const{name,password}=req.body;if(!name||!password||name.length<2||password.length<4)return res.json({ok:false,msg:'Invalid'});if(users[name])return res.json({ok:false,msg:'已存在'});users[name]={name,password,gold:800,chars:['soldier','ninja','tank'],wins:0,kills:0};save();res.json({ok:true});});
app.post('/api/login',(req,res)=>{const{name,password}=req.body;const u=users[name];if(!u||u.password!==password)return res.json({ok:false,msg:'错误'});const t=uid();u.token=t;save();res.json({ok:true,token:t,chars:u.chars,gold:u.gold,wins:u.wins,kills:u.kills});});
app.get('/api/online',(req,res)=>{var c=0;for(const id in rooms)c+=rooms[id].players.length;res.json({count:c});});app.get('/api/leaderboard',(req,res)=>{res.json(Object.values(users).sort((a,b)=>b.wins-a.wins).slice(0,50).map(u=>({name:u.name,wins:u.wins,kills:u.kills})));});
app.post('/api/buy',(req,res)=>{const{name,char}=req.body;const u=users[name];if(!u)return res.json({ok:false});const prices={ninja:300,tank:500,ghost:800,medic:600};if(u.chars.includes(char))return res.json({ok:false,msg:'已拥有'});if(u.gold<(prices[char]||200))return res.json({ok:false,msg:'金币不足'});u.gold-=prices[char]||200;u.chars.push(char);save();res.json({ok:true,gold:u.gold,chars:u.chars});});

function createRoom(type){const cfg={solo:{max:30,teamSize:1},duo:{max:40,teamSize:2},squad:{max:40,teamSize:4}}[type];const room={id:uid(),type,players:[],firstBlood:false,state:'waiting',circle:{x:MAP_W/2,y:MAP_H/2,r:1800},items:[],projectiles:[],grenades:[],particles:[],kills:[],emotes:[],airdrops:[],pings:[],chats:[],cfg,buildings:BUILDINGS,terrain:TERRAIN,airdropTimer:0,startTime:0};for(let i=0;i<200;i++){const t=Math.random();room.items.push({id:i,x:100+Math.random()*(MAP_W-200),y:100+Math.random()*(MAP_H-200),type:t<.1?'health':t<.16?'armor':t<.2?'scope':t<.28?'ammo_rifle':t<.34?'ammo_shotgun':t<.38?'ammo_sniper':t<.44?'rifle':t<.48?'shotgun':t<.5?'sniper':t<.52?'smg':t<.53?'rpg':t<.58?'grenade':'ammo'});}rooms[room.id]=room;return room;}
function findRoom(type){for(const id in rooms){const r=rooms[id];if(r.type===type&&r.state==='waiting'&&r.players.length<r.cfg.max)return r;}return createRoom(type);}
function broadcast(room,msg,exclude){room.players.forEach(p=>{if(p.ws.readyState===1&&(!exclude||p.id!==exclude))p.ws.send(JSON.stringify(msg));});}
function send(ws,msg){if(ws.readyState===1)ws.send(JSON.stringify(msg));}
function spawnAirdrop(room){if(room.state!=='playing')return;const x=300+Math.random()*(MAP_W-600),y=300+Math.random()*(MAP_H-600);room.airdrops.push({id:uid(),x,y,timer:200,opened:false});broadcast(room,{type:'airdrop',x,y});}

function tickRoom(room){
  if(room.state!=='playing')return;
  room.circle.r=Math.max(80,room.circle.r-(0.2+0.0001*(1800-room.circle.r)));
  room.airdropTimer++;if(room.airdropTimer>1800){room.airdropTimer=0;spawnAirdrop(room);}
  room.airdrops.forEach(ad=>{if(ad.timer>0)ad.timer--;});
  room.players.forEach(p=>{
    if(!p.alive)return;const spd=(p.sprinting?1.5:1)*(p.char==='ninja'?5.5:p.char==='tank'?3:4);
    if(p.speedX||p.speedY){const m=Math.hypot(p.speedX,p.speedY);var nx=p.x+p.speedX/m*spd,ny=p.y+p.speedY/m*spd;var blocked=false;for(const b of room.buildings){if(nx>p.x?p.x<b.x&&nx>b.x:nx<b.x&&p.x>b.x){if(ny>p.y?p.y<b.y&&ny>b.y:ny<b.y&&p.y>b.y){if(nx>b.x&&nx<b.x+b.w&&ny>b.y&&ny<b.y+b.h)blocked=true;}}}if(!blocked){p.x=nx;p.y=ny;}p.x=Math.max(20,Math.min(MAP_W-20,p.x));p.y=Math.max(20,Math.min(MAP_H-20,p.y));}
    if(dist(p,room.circle)>room.circle.r){p.hp-=1.5;if(p.hp<=0)killPlayer(room,p,null);}
    const wp=WEAPONS[p.weapon]||WEAPONS.pistol;
    if(p.shooting&&Date.now()-(p.lastShot||0)>wp.cd){p.lastShot=Date.now();const a=p.shootAngle;if(wp.pellets){for(let i=0;i<wp.pellets;i++)room.projectiles.push({x:p.x,y:p.y,vx:Math.cos(a+(Math.random()-.5)*wp.spread),vy:Math.sin(a+(Math.random()-.5)*wp.spread),shooter:p.id,dmg:wp.dmg,life:50,speed:wp.spd});}else room.projectiles.push({x:p.x,y:p.y,vx:Math.cos(a),vy:Math.sin(a),shooter:p.id,dmg:wp.dmg,life:70,speed:wp.spd,explosive:wp.explosive||false});if(p.weapon!=='pistol'){p.ammo--;if(p.ammo<=0)p.weapon='pistol';}}
    for(let i=room.items.length-1;i>=0;i--){const it=room.items[i];if(dist(p,it)<32){
      if(it.type==='health')p.hp=Math.min(p.char==='tank'?150:100,p.hp+(p.char==='medic'?45:30));
      else if(it.type==='armor')p.armor=Math.min(75,(p.armor||0)+30);else if(it.type==='scope')p.scope=true;
      else if(it.type==='rifle'){p.weapon='rifle';p.ammo=30;}else if(it.type==='shotgun'){p.weapon='shotgun';p.ammo=8;}else if(it.type==='sniper'){p.weapon='sniper';p.ammo=5;}else if(it.type==='smg'){p.weapon='smg';p.ammo=50;}else if(it.type==='rpg'){p.weapon='rpg';p.ammo=3;}
      else if(it.type==='grenade')p.grenades=(p.grenades||0)+1;
      else if(it.type==='ammo_rifle'&&p.weapon==='rifle')p.ammo=Math.min(90,p.ammo+15);
      else if(it.type==='ammo_shotgun'&&p.weapon==='shotgun')p.ammo=Math.min(24,p.ammo+4);
      else if(it.type==='ammo_sniper'&&p.weapon==='sniper')p.ammo=Math.min(15,p.ammo+2);
      else p.ammo=Math.min(30,p.ammo+8);
      room.items.splice(i,1);break;
    }}
    for(const ad of room.airdrops){if(!ad.opened&&ad.timer<=0&&dist(p,ad)<40){ad.opened=true;p.weapon='rpg';p.ammo=3;p.armor=Math.min(75,(p.armor||0)+50);p.hp=Math.min(p.char==='tank'?150:100,p.hp+50);p.grenades=(p.grenades||0)+2;for(let i=0;i<15;i++)room.particles.push({x:ad.x,y:ad.y,vx:(Math.random()-.5)*6,vy:(Math.random()-.5)*6,life:20,color:'#d2991d'});broadcast(room,{type:'airdropOpened',x:ad.x,y:ad.y,player:p.name});break;}}
    if(p.throwGrenade){p.throwGrenade=false;if((p.grenades||0)>0){p.grenades--;room.grenades.push({x:p.x,y:p.y,vx:Math.cos(p.throwAngle||0)*8,vy:Math.sin(p.throwAngle||0)*8,timer:80,shooter:p.id});}}
  });
  for(let i=room.airdrops.length-1;i>=0;i--)if(room.airdrops[i].opened)room.airdrops.splice(i,1);
  for(let i=room.projectiles.length-1;i>=0;i--){const pr=room.projectiles[i];pr.x+=pr.vx*pr.speed;pr.y+=pr.vy*pr.speed;pr.life--;var hitWall=false;for(const b of room.buildings)if(pr.x>b.x&&pr.x<b.x+b.w&&pr.y>b.y&&pr.y<b.y+b.h)hitWall=true;if(pr.x<0||pr.x>MAP_W||pr.y<0||pr.y>MAP_H||pr.life<=0||hitWall){if(pr.explosive&&hitWall){for(const p of room.players){if(!p.alive)continue;if(dist(pr,p)<100){var dmg2=80*(1-dist(pr,p)/100);if(p.armor>0){var a=Math.min(p.armor,Math.floor(dmg2*.5));p.armor-=a;dmg2-=a;}p.hp-=dmg2;if(p.hp<=0)killPlayer(room,p,room.players.find(x=>x.id===pr.shooter));}}for(let j=0;j<20;j++)room.particles.push({x:pr.x,y:pr.y,vx:(Math.random()-.5)*12,vy:(Math.random()-.5)*12,life:30,color:'#f04e30'});}room.projectiles.splice(i,1);continue;}for(const p of room.players){if(!p.alive||p.id===pr.shooter)continue;if(dist(pr,p)<22){var dmg=pr.dmg;if(p.armor>0){var a=Math.min(p.armor,Math.floor(dmg*.5));p.armor-=a;dmg-=a;}p.hp-=dmg;if(pr.explosive){for(const q of room.players){if(!q.alive||q.id===pr.shooter||q.id===p.id)continue;if(dist(pr,q)<80){var d2=50*(1-dist(pr,q)/80);if(q.armor>0){var a2=Math.min(q.armor,Math.floor(d2*.5));q.armor-=a2;d2-=a2;}q.hp-=d2;if(q.hp<=0)killPlayer(room,q,room.players.find(x=>x.id===pr.shooter));}}for(let j=0;j<15;j++)room.particles.push({x:pr.x,y:pr.y,vx:(Math.random()-.5)*10,vy:(Math.random()-.5)*10,life:25,color:'#f04e30'});}room.projectiles.splice(i,1);if(p.hp<=0)killPlayer(room,p,room.players.find(x=>x.id===pr.shooter));break;}}}
  for(let i=room.grenades.length-1;i>=0;i--){const g=room.grenades[i];g.x+=g.vx;g.y+=g.vy;g.timer--;if(g.timer<=0){for(let j=0;j<15;j++)room.particles.push({x:g.x,y:g.y,vx:(Math.random()-.5)*10,vy:(Math.random()-.5)*10,life:30,color:'#f04e30'});for(const p of room.players){if(!p.alive)continue;if(dist(g,p)<80){var dmg2=50*(1-dist(g,p)/80);if(p.armor>0){var a=Math.min(p.armor,Math.floor(dmg2*.5));p.armor-=a;dmg2-=a;}p.hp-=dmg2;if(p.hp<=0)killPlayer(room,p,room.players.find(x=>x.id===g.shooter));}}room.grenades.splice(i,1);}}
  for(let i=room.particles.length-1;i>=0;i--){room.particles[i].life--;if(room.particles[i].life<=0)room.particles.splice(i,1);}
  for(let i=room.emotes.length-1;i>=0;i--){room.emotes[i].life--;if(room.emotes[i].life<=0)room.emotes.splice(i,1);}
  for(let i=room.chats.length-1;i>=0;i--){if(Date.now()-room.chats[i].time>15000)room.chats.splice(i,1);}for(let i=room.pings.length-1;i>=0;i--){if(Date.now()-room.pings[i].time>5000)room.pings.splice(i,1);}
  const alive=room.players.filter(p=>p.alive);if(alive.length<=1&&room.players.length>1)endRoom(room,alive[0]);
  room.players.forEach(p=>{const alivePlayers=room.players.filter(x=>x.alive);var specIdx=-1,specTarget=null;if(!p.alive){const others=alivePlayers.filter(x=>x.id!==p.id);if(others.length>0){const idx=Math.min(p.spectateIdx||0,others.length-1);specTarget=others[idx];specIdx=idx;}}
  send(p.ws,{type:'state',me:{x:p.x,y:p.y,hp:p.hp,armor:p.armor,ammo:p.ammo,weapon:p.weapon,kills:p.kills,grenades:p.grenades,alive:p.alive,spectateCount:alivePlayers.length-1,placement:p.placement},players:room.players.map(x=>({id:x.id,x:x.x,y:x.y,hp:x.hp,armor:x.armor,alive:x.alive,char:x.char,name:x.name,weapon:x.weapon,team:x.team,crouching:x.crouching,sprinting:x.sprinting})),circle:room.circle,items:room.items.filter(it=>dist(p,it)<500),projectiles:room.projectiles.filter(pr=>dist(p,pr)<550),grenades:room.grenades.filter(g=>dist(p,g)<500),airdrops:room.airdrops.filter(ad=>dist(p,ad)<800),particles:room.particles.filter(pt=>dist(p,pt)<600),kills:room.kills.slice(-5),emotes:room.emotes.slice(-10),pings:room.pings?room.pings.slice(-5):[],chats:room.chats.slice(-10),teammates:room.players.filter(x=>x.team===p.team&&x.id!==p.id).map(x=>({id:x.id,x:x.x,y:x.y,hp:x.hp,name:x.name})),aliveCount:alive.length,buildings:room.buildings,terrain:TERRAIN,specTarget:specTarget?{x:specTarget.x,y:specTarget.y,name:specTarget.name}:null,specIdx,gameTime:Date.now()-room.startTime});});
}

function killPlayer(room,v,k){v.alive=false;if(k){k.kills++;k.streak=(k.streak||0)+1;k.multis=(k.multis||0)+1;setTimeout(()=>k.multis=0,3000);if(k.multis>=2){var mk={2:"双杀",3:"三杀",4:"四杀",5:"五杀"}[k.multis];if(mk)broadcast(room,{type:"multikill",player:k.name,count:k.multis,label:mk});}if(k.streak>=3&&k.streak%3===0)broadcast(room,{type:'killstreak',player:k.name,streak:k.streak});for(let i=0;i<12;i++)room.particles.push({x:v.x,y:v.y,vx:(Math.random()-.5)*10,vy:(Math.random()-.5)*10,life:25,color:'#f85149'});var kd=Math.floor(dist(k,v));room.kills.push({killer:k.name,victim:v.name,weapon:k.weapon,time:Date.now(),dist:kd});if(!room.firstBlood){room.firstBlood=true;broadcast(room,{type:"firstblood",killer:k.name,victim:v.name});}room.items.push({id:uid(),x:v.x,y:v.y,type:v.weapon==='sniper'?'sniper':v.weapon==='rpg'?'rpg':v.weapon==='rifle'?'rifle':v.weapon==='shotgun'?'shotgun':'health'});if(v.armor>0)room.items.push({id:uid(),x:v.x+10,y:v.y+10,type:'armor'});}if(!v.placement){var dead=room.players.filter(p=>!p.alive).length;v.placement=room.players.length-dead+1;}const a=room.players.filter(p=>p.alive);if(a.length<=1)endRoom(room,a[0]);
if(v.team!==undefined){const teamAlive=room.players.filter(p=>p.alive&&p.team===v.team);if(teamAlive.length===0){broadcast(room,{type:"aced",team:v.team});}}}
function endRoom(room,w){room.state='ended';if(w){const u=users[w.name];if(u){u.wins++;u.gold+=200+w.kills*30;save();}room.players.forEach(pl=>{if(!pl.placement)pl.placement=pl.alive?1:2;});broadcast(room,{type:'win',winner:w.name,kills:w.kills,weapon:w.weapon,gold:200+w.kills*30,total:room.players.length});}setTimeout(()=>delete rooms[room.id],20000);}
function startRoom(room){room.state='playing';room.startTime=Date.now();const sp=[{x:400,y:400},{x:MAP_W-400,y:400},{x:400,y:MAP_H-400},{x:MAP_W-400,y:MAP_H-400},{x:MAP_W/2,y:400},{x:MAP_W/2,y:MAP_H-400},{x:400,y:MAP_H/2},{x:MAP_W-400,y:MAP_H/2}];room.players.forEach((p,i)=>{p.x=sp[i%8].x+(Math.random()-.5)*300;p.y=sp[i%8].y+(Math.random()-.5)*300;p.hp=p.char==='tank'?150:100;p.armor=0;p.ammo=999;p.alive=true;p.weapon='pistol';p.kills=0;p.grenades=0;p.spectateIdx=0;p.streak=0;});room.airdropTimer=1200;broadcast(room,{type:'start'});}

wss.on('connection',(ws)=>{ws.playerId=uid();ws.roomId=null;ws.userName=null;
  ws.on('message',(raw)=>{let msg;try{msg=JSON.parse(raw);}catch(e){return;}
    if(msg.type==='auth'){const u=users[msg.name];if(!u||u.token!==msg.token){send(ws,{type:'error',msg:'Auth'});return;}ws.userName=msg.name;}
    if(msg.type==='join'){if(!ws.userName)return;const room=findRoom(msg.mode);const ti=Math.floor(room.players.length/room.cfg.teamSize);room.players.push({id:ws.playerId,name:ws.userName,char:msg.char||'soldier',x:0,y:0,hp:100,armor:0,ammo:999,alive:true,kills:0,grenades:0,speedX:0,speedY:0,weapon:'pistol',lastShot:0,shooting:false,shootAngle:0,throwGrenade:false,throwAngle:0,spectateIdx:0,team:ti,ws});ws.roomId=room.id;send(ws,{type:'joined',roomId:room.id,playerCount:room.players.length});broadcast(room,{type:'players',count:room.players.length});if(room.players.length>=2&&room.state==='waiting'){const c=()=>{broadcast(room,{type:'countdown',sec:3});setTimeout(()=>{broadcast(room,{type:'countdown',sec:2});setTimeout(()=>{broadcast(room,{type:'countdown',sec:1});setTimeout(()=>startRoom(room),1000);},1000);},1000);};setTimeout(c,1500);}}
    if(msg.type==='move'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive){p.speedX=msg.x||0;p.speedY=msg.y||0;p.sprinting=msg.sprinting||false;}}
    if(msg.type==='shoot'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive){p.shooting=msg.active;if(msg.angle!==undefined)p.shootAngle=msg.angle;}}
    if(msg.type==='grenade'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive){p.throwGrenade=true;p.throwAngle=msg.angle;}}
    if(msg.type==='reload'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive&&p.weapon!=='pistol'){const wp=WEAPONS[p.weapon];if(wp){p.ammo=wp.ammo;}}}
    if(msg.type==='ability'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(!p||!p.alive)return;const now=Date.now();if(p.lastAbility&&now-p.lastAbility<15000)return;p.lastAbility=now;if(p.char==='ninja'){for(let i=0;i<20;i++)room.particles.push({x:p.x+(Math.random()-.5)*60,y:p.y+(Math.random()-.5)*60,vx:0,vy:0,life:30,color:'#bc8cff'});broadcast(room,{type:'abilityEffect',char:'ninja',x:p.x,y:p.y});}else if(p.char==='medic'){p.hp=Math.min(p.char==='tank'?150:100,p.hp+30);broadcast(room,{type:'abilityEffect',char:'medic',x:p.x,y:p.y});}else if(p.char==='tank'){p.armor=Math.min(75,(p.armor||0)+20);broadcast(room,{type:'abilityEffect',char:'tank',x:p.x,y:p.y});}else if(p.char==='ghost'){p.invisible=true;setTimeout(()=>p.invisible=false,3000);broadcast(room,{type:'abilityEffect',char:'ghost',x:p.x,y:p.y});}else{broadcast(room,{type:'abilityEffect',char:'soldier',x:p.x,y:p.y});}}if(msg.type==='ping'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;room.pings.push({x:msg.x,y:msg.y,name:ws.userName,time:Date.now()});broadcast(room,{type:'ping',x:msg.x,y:msg.y,name:ws.userName,time:Date.now()});}if(msg.type==='crouch'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive){if(msg.sliding&&!p.crouching){p.sliding=true;p.crouching=true;setTimeout(()=>{p.sliding=false;p.crouching=false;},500);}else{p.crouching=!p.crouching;p.sliding=false;}}}if(msg.type==='emote'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive)room.emotes.push({playerId:ws.playerId,x:p.x,y:p.y,emoji:msg.emoji,life:40});}
    if(msg.type==='chat'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p){room.chats.push({name:p.name,text:msg.text,time:Date.now()});broadcast(room,{type:'chat',name:p.name,text:msg.text,all:true});}}
    if(msg.type==='switchweapon'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p&&p.alive){p.weapon=msg.weapon;}}
    if(msg.type==='spectate'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;const p=room.players.find(x=>x.id===ws.playerId);if(p)p.spectateIdx=msg.idx;}
    if(msg.type==='leave'){if(!ws.roomId)return;const room=rooms[ws.roomId];if(!room)return;room.players=room.players.filter(x=>x.id!==ws.playerId);broadcast(room,{type:'players',count:room.players.length});ws.roomId=null;}
  });
  ws.on('close',()=>{if(ws.roomId){const room=rooms[ws.roomId];if(room){room.players=room.players.filter(x=>x.id!==ws.playerId);broadcast(room,{type:'players',count:room.players.length});}}});
});
setInterval(()=>{for(const id in rooms)tickRoom(rooms[id]);},TICK);
server.listen(3000,()=>console.log('Battle Royale v14 :3000'));
