// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadRuntimeLifecycle = {
/**
 * Identifier of the currently active turn, when app-server has one.
 */
activeTurnId: string | null,
/**
 * Unix timestamp (in seconds) when the active turn started, if known.
 */
activeTurnStartedAt: number | null,
/**
 * Identifier of the latest terminal turn observed by the live thread listener.
 */
lastTerminalTurnId: string | null, };
