// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";
import type { ThreadRuntimeLifecycle } from "./ThreadRuntimeLifecycle";

export type ThreadReadResponse = { thread: Thread,
/**
 * Lightweight, content-free runtime evidence for lifecycle reconciliation.
 * Older app-server builds omit this field.
 */
runtimeLifecycle: ThreadRuntimeLifecycle | null, };
