// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnItemsView } from "./TurnItemsView";

export type ThreadReadParams = { threadId: string,
/**
 * When true, include turns and their items from rollout history.
 */
includeTurns?: boolean,
/**
 * How much item detail to include for each returned turn; defaults to full
 * when `includeTurns` is true.
 */
itemsView?: TurnItemsView | null, };
