// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContextTokenUsageSource } from "./ContextTokenUsageSource";
import type { TokenUsageBreakdown } from "./TokenUsageBreakdown";

export type ThreadTokenUsage = { total: TokenUsageBreakdown, last: TokenUsageBreakdown, contextTokens: number | null, contextSource: ContextTokenUsageSource | null, modelContextWindow: number | null, };
