// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscriptMetadata = { turnId: string | null, backendItemId: string | null, orderIndex: number | null, eventSequence: number | null, };
