//! Shared tool definitions and Responses API tool primitives that can live
//! outside `codex-core`.

mod claude_native;
mod code_mode;
mod dynamic_tool;
mod function_call_error;
mod image_detail;
mod json_schema;
mod mcp_tool;
mod request_plugin_install;
mod response_history;
mod responses_api;
mod tool_call;
mod tool_config;
mod tool_definition;
mod tool_discovery;
mod tool_executor;
mod tool_output;
mod tool_payload;
mod tool_search;
mod tool_spec;

pub use claude_native::CLAUDE_ADVISOR_20260301_TOOL_TYPE;
pub use claude_native::CLAUDE_ADVISOR_TOOL_NAME;
pub use claude_native::CLAUDE_BASH_20250124_TOOL_TYPE;
pub use claude_native::CLAUDE_BASH_TOOL_NAME;
pub use claude_native::CLAUDE_CODE_EXECUTION_20250825_TOOL_TYPE;
pub use claude_native::CLAUDE_CODE_EXECUTION_20260120_TOOL_TYPE;
pub use claude_native::CLAUDE_CODE_EXECUTION_TOOL_NAME;
pub use claude_native::CLAUDE_COMPUTER_20250124_TOOL_TYPE;
pub use claude_native::CLAUDE_COMPUTER_20251124_TOOL_TYPE;
pub use claude_native::CLAUDE_COMPUTER_TOOL_NAME;
pub use claude_native::CLAUDE_MCP_TOOLSET_TOOL_TYPE;
pub use claude_native::CLAUDE_MEMORY_20250818_TOOL_TYPE;
pub use claude_native::CLAUDE_MEMORY_TOOL_NAME;
pub use claude_native::CLAUDE_TEXT_EDITOR_20250124_TOOL_TYPE;
pub use claude_native::CLAUDE_TEXT_EDITOR_20250728_TOOL_TYPE;
pub use claude_native::CLAUDE_TEXT_EDITOR_TOOL_NAME;
pub use claude_native::CLAUDE_TOOL_SEARCH_BM25_20251119_TOOL_TYPE;
pub use claude_native::CLAUDE_TOOL_SEARCH_BM25_TOOL_NAME;
pub use claude_native::CLAUDE_TOOL_SEARCH_REGEX_20251119_TOOL_TYPE;
pub use claude_native::CLAUDE_TOOL_SEARCH_REGEX_TOOL_NAME;
pub use claude_native::CLAUDE_TOOL_SEARCH_TOOL_NAME;
pub use claude_native::CLAUDE_WEB_FETCH_20250910_TOOL_TYPE;
pub use claude_native::CLAUDE_WEB_FETCH_20260209_TOOL_TYPE;
pub use claude_native::CLAUDE_WEB_FETCH_TOOL_NAME;
pub use claude_native::CLAUDE_WEB_SEARCH_20250305_TOOL_TYPE;
pub use claude_native::CLAUDE_WEB_SEARCH_20260209_TOOL_TYPE;
pub use claude_native::CLAUDE_WEB_SEARCH_TOOL_NAME;
pub use claude_native::ClaudeBetaFeature;
pub use claude_native::ClaudeHistoryRequirements;
pub use claude_native::ClaudeLocalExecutorCapability;
pub use claude_native::ClaudeMcpServer;
pub use claude_native::ClaudeMcpToolsetConfig;
pub use claude_native::ClaudeNativeToolDecision;
pub use claude_native::ClaudeNativeToolDecisionOutcome;
pub use claude_native::ClaudeNativeToolExecution;
pub use claude_native::ClaudeNativeToolKind;
pub use claude_native::ClaudeNativeToolPolicy;
pub use claude_native::ClaudeNativeToolSelection;
pub use claude_native::ClaudeProviderPlatform;
pub use claude_native::ClaudeServerCapability;
pub use claude_native::evaluate_native_tool;
pub use code_mode::augment_tool_spec_for_code_mode;
pub use code_mode::code_mode_name_for_tool_name;
pub use code_mode::collect_code_mode_exec_prompt_tool_definitions;
pub use code_mode::collect_code_mode_tool_definitions;
pub use code_mode::tool_spec_to_code_mode_tool_definition;
pub use codex_protocol::ToolName;
pub use dynamic_tool::parse_dynamic_tool;
pub use function_call_error::FunctionCallError;
pub use image_detail::can_request_original_image_detail;
pub use image_detail::normalize_output_image_detail;
pub use image_detail::sanitize_original_image_detail;
pub use json_schema::AdditionalProperties;
pub use json_schema::JsonSchema;
pub use json_schema::JsonSchemaPrimitiveType;
pub use json_schema::JsonSchemaType;
pub use json_schema::parse_tool_input_schema;
pub use json_schema::parse_tool_input_schema_without_compaction;
pub use mcp_tool::mcp_call_tool_result_output_schema;
pub use mcp_tool::parse_mcp_tool;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_APPROVAL_KIND_VALUE;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_PERSIST_ALWAYS_VALUE;
pub use request_plugin_install::REQUEST_PLUGIN_INSTALL_PERSIST_KEY;
pub use request_plugin_install::RequestPluginInstallArgs;
pub use request_plugin_install::RequestPluginInstallMeta;
pub use request_plugin_install::RequestPluginInstallResult;
pub use request_plugin_install::all_requested_connectors_picked_up;
pub use request_plugin_install::build_request_plugin_install_elicitation_request;
pub use request_plugin_install::verified_connector_install_completed;
pub use response_history::retain_tail_from_last_n_user_messages;
pub use response_history::truncate_assistant_output_text_to_token_budget;
pub use responses_api::FreeformTool;
pub use responses_api::FreeformToolFormat;
pub use responses_api::LoadableToolSpec;
pub use responses_api::ResponsesApiNamespace;
pub use responses_api::ResponsesApiNamespaceTool;
pub use responses_api::ResponsesApiTool;
pub use responses_api::coalesce_loadable_tool_specs;
pub use responses_api::default_namespace_description;
pub use responses_api::dynamic_tool_to_responses_api_tool;
pub use responses_api::mcp_tool_to_deferred_responses_api_tool;
pub use responses_api::mcp_tool_to_responses_api_tool;
pub use responses_api::tool_definition_to_responses_api_tool;
pub use tool_call::ConversationHistory;
pub use tool_call::ExtensionTurnItem;
pub use tool_call::NoopTurnItemEmitter;
pub use tool_call::ToolCall;
pub use tool_call::TurnItemEmissionFuture;
pub use tool_call::TurnItemEmitter;
pub use tool_config::ShellCommandBackendConfig;
pub use tool_config::ToolEnvironmentMode;
pub use tool_config::ToolUserShellType;
pub use tool_config::UnifiedExecFeatureMode;
pub use tool_config::UnifiedExecShellMode;
pub use tool_config::ZshForkConfig;
pub use tool_config::request_user_input_available_modes;
pub use tool_config::shell_command_backend_for_features;
pub use tool_config::shell_type_for_model_and_features;
pub use tool_config::unified_exec_feature_mode_for_features;
pub use tool_definition::ToolDefinition;
pub use tool_discovery::DiscoverablePluginInfo;
pub use tool_discovery::DiscoverableTool;
pub use tool_discovery::DiscoverableToolAction;
pub use tool_discovery::DiscoverableToolType;
pub use tool_discovery::LIST_AVAILABLE_PLUGINS_TO_INSTALL_TOOL_NAME;
pub use tool_discovery::ListAvailablePluginsToInstallResult;
pub use tool_discovery::REQUEST_PLUGIN_INSTALL_TOOL_NAME;
pub use tool_discovery::RequestPluginInstallEntry;
pub use tool_discovery::TOOL_SEARCH_DEFAULT_LIMIT;
pub use tool_discovery::TOOL_SEARCH_TOOL_NAME;
pub use tool_discovery::ToolSearchSourceInfo;
pub use tool_discovery::collect_request_plugin_install_entries;
pub use tool_discovery::filter_request_plugin_install_discoverable_tools_for_client;
pub use tool_executor::ToolExecutor;
pub use tool_executor::ToolExposure;
pub use tool_output::JsonToolOutput;
pub use tool_output::ToolOutput;
pub use tool_payload::ToolPayload;
pub use tool_search::ToolSearchEntry;
pub use tool_search::ToolSearchInfo;
pub use tool_search::default_tool_search_text;
pub use tool_spec::ClaudeMessagesToolOptions;
pub use tool_spec::ClaudeToolCallInfo;
pub use tool_spec::ClaudeToolCallKind;
pub use tool_spec::ClaudeToolsJson;
pub use tool_spec::ClaudeWebSearchToolKind;
pub use tool_spec::ResponsesApiWebSearchFilters;
pub use tool_spec::ResponsesApiWebSearchUserLocation;
pub use tool_spec::ToolSpec;
pub use tool_spec::claude_tool_name;
pub use tool_spec::create_tools_json_for_claude_messages;
pub use tool_spec::create_tools_json_for_claude_messages_with_options;
pub use tool_spec::create_tools_json_for_responses_api;
