// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Citation = { provider: string, type: string, title?: string, url?: string, citedText?: string, encryptedIndex?: string, documentIndex?: bigint, startPageNumber?: bigint, endPageNumber?: bigint, startCharIndex?: bigint, endCharIndex?: bigint, raw?: unknown, };
